In [2]:
import torch
import numpy as np

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [4]:
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8484, 0.5636],
        [0.0335, 0.1902]]) 



In [7]:
tensor = torch.ones(4, 4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
tensor[0,-1] = 2
tensor

tensor([[1., 1., 1., 2.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 5.]])

In [18]:
tensor = torch.cat([tensor, tensor, tensor], dim = 0)
tensor

tensor([[1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1.,
         1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
         1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
         1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 5., 1., 1., 1., 5., 1., 1., 1., 5., 1., 1., 1., 5., 1., 1.,
         1., 5., 1., 1., 1., 5., 1., 1., 1., 5., 1., 1., 1., 5., 1., 1., 1., 5.],
        [1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1.,
         1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
         1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0

In [20]:
y1 = tensor @ tensor.T
y1

tensor([[ 63.,  27.,  27., 117.,  63.,  27.,  27., 117.,  63.,  27.,  27., 117.],
        [ 27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.],
        [ 27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.],
        [117.,  27.,  27., 252., 117.,  27.,  27., 252., 117.,  27.,  27., 252.],
        [ 63.,  27.,  27., 117.,  63.,  27.,  27., 117.,  63.,  27.,  27., 117.],
        [ 27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.],
        [ 27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.],
        [117.,  27.,  27., 252., 117.,  27.,  27., 252., 117.,  27.,  27., 252.],
        [ 63.,  27.,  27., 117.,  63.,  27.,  27., 117.,  63.,  27.,  27., 117.],
        [ 27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.],
        [ 27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.,  27.],
        [117.,  27.,  27., 252., 117.,  27.,  27., 252., 117.,  27.,  27., 252.]])